CREATE TABLE OPCOES_RESPOSTAS (
    ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    DESCRICAO VARCHAR(512) NOT NULL,
    ID_PERGUNTAS INT,
    PERGUNTA_ROUTE INT,
    FOREIGN KEY (ID_PERGUNTAS) REFERENCES PERGUNTAS(ID)
);