CREATE TABLE USUARIOS (
    ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    DATA_NASC DATE NOT NULL,
    CPF NUMERIC(11) NOT NULL,
    SEXO VARCHAR(50) NULL,
    DATA_CADASTRO DATETIME NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    PASSWORD VARCHAR(250) NOT NULL,
    ACTIVE BIT
);