CREATE TABLE USUARIO_ADMIN (
    ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    NAME VARCHAR(256) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    PASSWORD VARCHAR(250) NOT NULL,
    ACTIVE BIT,
    ID_PERFIL INT,
    FOREIGN KEY (ID_PERFIL) REFERENCES PERFIL(ID)